/*
  # Create Calculation History Table
  
  1. New Tables
    - `calculation_history`
      - `id` (bigint, auto-generated primary key)
      - `expression` (text, the math expression)
      - `result` (text, the calculation result)
      - `created_at` (timestamp with timezone, auto-set to now)
  
  2. Security
    - Enable RLS so anyone can insert and read calculations
    - Add policy for public access (no authentication required)
*/

CREATE TABLE IF NOT EXISTS calculation_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expression TEXT NOT NULL,
  result TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE calculation_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert"
  ON calculation_history
  FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Allow public select"
  ON calculation_history
  FOR SELECT
  TO anon
  USING (true);
